### ISSUE TITLE
Use for MRA data

### ISSUE THREAD

**Issue by saro92** [MIC-DKFZ/HD-BET#20]
Hi

very nice work and so helpful but can this tool been used for magnetic resonance angiography brain extraction?

I look forward to your reply.
Regards.

**Comment by FabianIsensee** [comment]
Hi,
I don't know what these images look like so I can't say. We have not trained on this modality so I would be surprised if it worked. You can just give it a try and see :-)
Best,
Fabian

**Comment by ShamSinha** [comment]
Hi,
I have tried this tool on MRA and found that it ignores the Circle of Willis region (where arteries meet in simple) but it works fine for most of the slices. 
Any suggestion what to do so that it works even for MRA
I look forward to your reply on this.

**Comment by FabianIsensee** [comment]
Hi @ShamSinha ,
like all deep learning models, HD-BET only works on data that is similar to its training cases. We have not trained on MRA data (simply because we didn't have any training cases for that) and therefore our tool can unfortunately not handle them properly. There is no way of fixing that except for finding MRA training cases and retraining the model
Best,
Fabian
